version: '3'

services:
    pg_db:
        image: postgres:13
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: green_taxi
        volumes:
            - ./green_taxi_data:/var/lib/postgresql/data
            
        ports:
          - "5436:5432"
    
    pgadmin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=root
      ports:
        - "8080:80"
      volumes:
        - vol-pgadmin_data:/var/lib/pgadmin

volumes:
  green_taxi_data:
    name: vol_green_taxi
 
  